// <auto-generated />
using System;
using Eliteracingleague.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eliteracingleague.API.Migrations
{
    [DbContext(typeof(EliteRacingLeagueContext))]
    [Migration("20260629083026_AddNotificationMetadataColumns")]
    partial class AddNotificationMetadataColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eliteracingleague.API.Models.EmailVerificationOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("otp_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_email_verification_otps");

                    b.HasIndex(new[] { "UserId", "IsUsed", "ExpiresAt" }, "IX_email_verification_otps_user_active");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_email_verification_otps_user_created_at");

                    b.ToTable("email_verification_otps", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Horse", b =>
                {
                    b.Property<int>("HorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("horse_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorseId"));

                    b.Property<string>("AchievementSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("achievement_summary");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<int>("BreedId")
                        .HasColumnType("int")
                        .HasColumnName("breed_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("HealthCertificateImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("health_certificate_image_url");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("health_status");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("HorseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("horse_name");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("HorseId")
                        .HasName("PK__horses__DE0BA8A246C3391C");

                    b.HasIndex("BreedId");

                    b.HasIndex("OwnerId");

                    b.ToTable("horses", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.HorseBreed", b =>
                {
                    b.Property<int>("BreedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("breed_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BreedId"));

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("breed_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("BreedId")
                        .HasName("PK__horse_br__9C02143508F51A03");

                    b.HasIndex(new[] { "BreedName" }, "UQ__horse_br__1026DC5C67469E99")
                        .IsUnique();

                    b.ToTable("horse_breeds", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.HorseOwner", b =>
                {
                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("OwnerId")
                        .HasName("PK__horse_ow__3C4FBEE407468D3B");

                    b.ToTable("horse_owners", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Jockey", b =>
                {
                    b.Property<int>("JockeyId")
                        .HasColumnType("int")
                        .HasColumnName("jockey_id");

                    b.Property<string>("CertificateFileUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("certificate_file_url");

                    b.Property<string>("CertificateNo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("certificate_no");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("HealthCertificateUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("health_certificate_url");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("health_status");

                    b.Property<string>("IdCardBackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("id_card_back_url");

                    b.Property<string>("IdCardFrontUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("id_card_front_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("profile_image_url");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weight_kg");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnName("years_of_experience");

                    b.HasKey("JockeyId")
                        .HasName("PK__jockeys__A37CBB381F9D6473");

                    b.ToTable("jockeys", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.JockeyAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("availability_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<DateOnly>("AvailableDate")
                        .HasColumnType("date")
                        .HasColumnName("available_date");

                    b.Property<int>("JockeyId")
                        .HasColumnType("int")
                        .HasColumnName("jockey_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("AvailabilityId")
                        .HasName("PK__jockey_a__86E3A8015CD4B330");

                    b.HasIndex(new[] { "JockeyId", "AvailableDate" }, "UQ_jockey_availabilities_jockey_date")
                        .IsUnique();

                    b.ToTable("jockey_availabilities", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.JockeyBreedExperience", b =>
                {
                    b.Property<int>("JockeyBreedExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("jockey_breed_experience_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JockeyBreedExperienceId"));

                    b.Property<int>("BreedId")
                        .HasColumnType("int")
                        .HasColumnName("breed_id");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("experience_level");

                    b.Property<int>("JockeyId")
                        .HasColumnType("int")
                        .HasColumnName("jockey_id");

                    b.HasKey("JockeyBreedExperienceId")
                        .HasName("PK__jockey_b__62791554F51F3E30");

                    b.HasIndex("BreedId");

                    b.HasIndex(new[] { "JockeyId", "BreedId" }, "UQ_jockey_breed_experiences_jockey_breed")
                        .IsUnique();

                    b.ToTable("jockey_breed_experiences", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.JockeyDistanceExperience", b =>
                {
                    b.Property<int>("JockeyDistanceExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("jockey_distance_experience_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JockeyDistanceExperienceId"));

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("int")
                        .HasColumnName("distance_meters");

                    b.Property<int>("JockeyId")
                        .HasColumnType("int")
                        .HasColumnName("jockey_id");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("skill_level");

                    b.HasKey("JockeyDistanceExperienceId")
                        .HasName("PK__jockey_d__3E2AD9BCB9A2A8CD");

                    b.HasIndex(new[] { "JockeyId", "DistanceMeters" }, "UQ_jockey_distance_experiences_jockey_distance")
                        .IsUnique();

                    b.ToTable("jockey_distance_experiences", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.JockeyInvitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invitation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<decimal?>("FeeAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fee_amount");

                    b.Property<int>("InvitedByOwnerId")
                        .HasColumnType("int")
                        .HasColumnName("invited_by_owner_id");

                    b.Property<int>("JockeyId")
                        .HasColumnType("int")
                        .HasColumnName("jockey_id");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("registration_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("responded_at");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("InvitationId")
                        .HasName("PK__jockey_i__94B74D7C5D75ED0F");

                    b.HasIndex("InvitedByOwnerId");

                    b.HasIndex("JockeyId");

                    b.HasIndex(new[] { "RegistrationId", "JockeyId" }, "UQ_jockey_invitations_registration_jockey")
                        .IsUnique();

                    b.ToTable("jockey_invitations", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.JockeyRecommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recommendation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationId"));

                    b.Property<int>("AvailabilityScore")
                        .HasColumnType("int")
                        .HasColumnName("availability_score");

                    b.Property<int>("BreedExperienceScore")
                        .HasColumnType("int")
                        .HasColumnName("breed_experience_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DistanceScore")
                        .HasColumnType("int")
                        .HasColumnName("distance_score");

                    b.Property<int>("ExperienceScore")
                        .HasColumnType("int")
                        .HasColumnName("experience_score");

                    b.Property<int>("HorseId")
                        .HasColumnType("int")
                        .HasColumnName("horse_id");

                    b.Property<int>("JockeyId")
                        .HasColumnType("int")
                        .HasColumnName("jockey_id");

                    b.Property<string>("OwnerDecision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("owner_decision");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<int>("RankNo")
                        .HasColumnType("int")
                        .HasColumnName("rank_no");

                    b.Property<string>("RecommendationLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("recommendation_level");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("registration_id");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int")
                        .HasColumnName("total_score");

                    b.Property<int>("WeightScore")
                        .HasColumnType("int")
                        .HasColumnName("weight_score");

                    b.HasKey("RecommendationId")
                        .HasName("PK__jockey_r__BCB11F4FDE99F9DB");

                    b.HasIndex("HorseId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("RaceId");

                    b.HasIndex(new[] { "RegistrationId", "JockeyId" }, "UQ_jockey_recommendations_registration_jockey")
                        .IsUnique();

                    b.HasIndex(new[] { "RegistrationId", "RankNo" }, "UQ_jockey_recommendations_registration_rank")
                        .IsUnique();

                    b.ToTable("jockey_recommendations", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action_type");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("action_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("message");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int")
                        .HasColumnName("related_id");

                    b.Property<string>("RelatedType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("related_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK__notifica__E059842F608095F5");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.PreRaceInspection", b =>
                {
                    b.Property<int>("InspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inspection_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionId"));

                    b.Property<DateTime>("InspectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("inspected_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("note");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int")
                        .HasColumnName("referee_id");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("registration_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("InspectionId")
                        .HasName("PK__pre_race__C3C4E743F6FE7C6D");

                    b.HasIndex("RefereeId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex(new[] { "RaceId", "RegistrationId" }, "UQ_pre_race_inspections_race_registration")
                        .IsUnique();

                    b.ToTable("pre_race_inspections", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.PrizeAward", b =>
                {
                    b.Property<int>("PrizeAwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prize_award_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrizeAwardId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("JockeyId")
                        .HasColumnType("int")
                        .HasColumnName("jockey_id");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<decimal>("PrizeAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("prize_amount");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<int>("RankPosition")
                        .HasColumnType("int")
                        .HasColumnName("rank_position");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("registration_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("PrizeAwardId")
                        .HasName("PK__prize_aw__14E95D184DD587F4");

                    b.HasIndex("JockeyId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex(new[] { "RaceId", "RankPosition" }, "UQ_prize_awards_race_rank")
                        .IsUnique();

                    b.ToTable("prize_awards", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.PrizeRule", b =>
                {
                    b.Property<int>("PrizeRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prize_rule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrizeRuleId"));

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<decimal>("PrizeAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("prize_amount");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<int>("RankPosition")
                        .HasColumnType("int")
                        .HasColumnName("rank_position");

                    b.HasKey("PrizeRuleId")
                        .HasName("PK__prize_ru__0BF66D14DD02975C");

                    b.HasIndex(new[] { "RaceId", "RankPosition" }, "UQ_prize_rules_race_rank")
                        .IsUnique();

                    b.ToTable("prize_rules", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("int")
                        .HasColumnName("distance_meters");

                    b.Property<DateTime?>("JockeySelectionDeadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("jockey_selection_deadline");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<int>("MaxHorses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("max_horses");

                    b.Property<DateTime?>("PredictionDeadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("prediction_deadline");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("race_date");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("race_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("tournament_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("RaceId")
                        .HasName("PK__races__1C8FE2F9C56EC77A");

                    b.HasIndex(new[] { "TournamentId" }, "UQ__races__B93AA09C53DC9C5A")
                        .IsUnique();

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RacePrediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prediction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredictionId"));

                    b.Property<int?>("ActualWinnerRegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("actual_winner_registration_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("evaluated_at");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("locked_at");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int")
                        .HasColumnName("points_awarded");

                    b.Property<DateTime>("PredictedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("predicted_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("PredictedRegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("predicted_registration_id");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<decimal?>("RewardAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("reward_amount");

                    b.Property<string>("RewardStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("reward_status");

                    b.Property<int>("SpectatorId")
                        .HasColumnType("int")
                        .HasColumnName("spectator_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PredictionId")
                        .HasName("PK__race_pre__F1AE77BF0CDAA820");

                    b.HasIndex("ActualWinnerRegistrationId");

                    b.HasIndex("PredictedRegistrationId");

                    b.HasIndex("SpectatorId");

                    b.HasIndex(new[] { "RaceId", "PredictedRegistrationId" }, "IX_race_predictions_race_predicted_registration");

                    b.HasIndex(new[] { "RaceId", "SpectatorId" }, "UQ_race_predictions_race_spectator")
                        .IsUnique();

                    b.ToTable("race_predictions", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RaceReferee", b =>
                {
                    b.Property<int>("RefereeId")
                        .HasColumnType("int")
                        .HasColumnName("referee_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LicenseNo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("license_no");

                    b.HasKey("RefereeId")
                        .HasName("PK__race_ref__28102F7A95FFDADE");

                    b.ToTable("race_referees", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RaceRegistration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("registration_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("admin_note");

                    b.Property<int>("HorseId")
                        .HasColumnType("int")
                        .HasColumnName("horse_id");

                    b.Property<DateTime?>("JockeyConfirmedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("jockey_confirmed_at");

                    b.Property<int?>("JockeyId")
                        .HasColumnType("int")
                        .HasColumnName("jockey_id");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("RegistrationId")
                        .HasName("PK__race_reg__22A298F69B7624C6");

                    b.HasIndex("HorseId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex(new[] { "RaceId", "HorseId" }, "UQ_race_registrations_race_horse")
                        .IsUnique();

                    b.HasIndex(new[] { "RaceId", "JockeyId" }, "UX_race_registrations_race_jockey")
                        .IsUnique()
                        .HasFilter("([jockey_id] IS NOT NULL)");

                    b.ToTable("race_registrations", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RaceResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("result_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int?>("AdminConfirmedBy")
                        .HasColumnType("int")
                        .HasColumnName("admin_confirmed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("EnteredByRefereeId")
                        .HasColumnType("int")
                        .HasColumnName("entered_by_referee_id");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("int")
                        .HasColumnName("finish_position");

                    b.Property<decimal?>("FinishTimeSeconds")
                        .HasColumnType("decimal(10, 3)")
                        .HasColumnName("finish_time_seconds");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("published_at");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("registration_id");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ResultId")
                        .HasName("PK__race_res__AFB3C316BEFC476E");

                    b.HasIndex("AdminConfirmedBy");

                    b.HasIndex("EnteredByRefereeId");

                    b.HasIndex(new[] { "RegistrationId" }, "UQ__race_res__22A298F7BC9E1690")
                        .IsUnique();

                    b.HasIndex(new[] { "RaceId", "FinishPosition" }, "UQ_race_results_race_position")
                        .IsUnique()
                        .HasFilter("[finish_position] IS NOT NULL");

                    b.ToTable("race_results", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RaceViolation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("violation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViolationId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("PenaltyPoints")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("penalty_points");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int")
                        .HasColumnName("referee_id");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("registration_id");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("violation_type");

                    b.HasKey("ViolationId")
                        .HasName("PK__race_vio__8A989363B6FEFAEF");

                    b.HasIndex("RaceId");

                    b.HasIndex("RefereeId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("race_violations", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RefereeAssignment", b =>
                {
                    b.Property<int>("RefereeAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("referee_assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefereeAssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int")
                        .HasColumnName("assigned_by");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int")
                        .HasColumnName("referee_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("RefereeAssignmentId")
                        .HasName("PK__referee___F075D2954BB95A24");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("RefereeId");

                    b.HasIndex(new[] { "RaceId", "RefereeId" }, "UQ_referee_assignments_race_referee")
                        .IsUnique();

                    b.ToTable("referee_assignments", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RefereeReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int")
                        .HasColumnName("referee_id");

                    b.Property<string>("ReportContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("report_content");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("report_type");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("ReportId")
                        .HasName("PK__referee___779B7C58B711E616");

                    b.HasIndex("RaceId");

                    b.HasIndex("RefereeId");

                    b.ToTable("referee_reports", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<int>("PointsPerCorrectPrediction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100)
                        .HasColumnName("points_per_correct_prediction");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("season_name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("SeasonId")
                        .HasName("PK_seasons");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tournament_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<int>("MaxHorses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("max_horses");

                    b.Property<decimal?>("PrizePool")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("prize_pool");

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rules");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("TournamentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tournament_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("TournamentId")
                        .HasName("PK__tourname__B93AA09D92CAF19D");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SeasonId");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("email_verified");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370F8BD4C6E0");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164C799B617")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.EmailVerificationOtp", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.User", "User")
                        .WithMany("EmailVerificationOtps")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_email_verification_otps_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Horse", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.HorseBreed", "Breed")
                        .WithMany("Horses")
                        .HasForeignKey("BreedId")
                        .IsRequired()
                        .HasConstraintName("FK_horses_horse_breeds");

                    b.HasOne("Eliteracingleague.API.Models.HorseOwner", "Owner")
                        .WithMany("Horses")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_horses_horse_owners");

                    b.Navigation("Breed");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.HorseOwner", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.User", "Owner")
                        .WithOne("HorseOwner")
                        .HasForeignKey("Eliteracingleague.API.Models.HorseOwner", "OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_horse_owners_users");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Jockey", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.User", "JockeyNavigation")
                        .WithOne("Jockey")
                        .HasForeignKey("Eliteracingleague.API.Models.Jockey", "JockeyId")
                        .IsRequired()
                        .HasConstraintName("FK_jockeys_users");

                    b.Navigation("JockeyNavigation");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.JockeyAvailability", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.Jockey", "Jockey")
                        .WithMany("JockeyAvailabilities")
                        .HasForeignKey("JockeyId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_availabilities_jockeys");

                    b.Navigation("Jockey");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.JockeyBreedExperience", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.HorseBreed", "Breed")
                        .WithMany("JockeyBreedExperiences")
                        .HasForeignKey("BreedId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_breed_experiences_breeds");

                    b.HasOne("Eliteracingleague.API.Models.Jockey", "Jockey")
                        .WithMany("JockeyBreedExperiences")
                        .HasForeignKey("JockeyId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_breed_experiences_jockeys");

                    b.Navigation("Breed");

                    b.Navigation("Jockey");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.JockeyDistanceExperience", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.Jockey", "Jockey")
                        .WithMany("JockeyDistanceExperiences")
                        .HasForeignKey("JockeyId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_distance_experiences_jockeys");

                    b.Navigation("Jockey");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.JockeyInvitation", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.HorseOwner", "InvitedByOwner")
                        .WithMany("JockeyInvitations")
                        .HasForeignKey("InvitedByOwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_invitations_owners");

                    b.HasOne("Eliteracingleague.API.Models.Jockey", "Jockey")
                        .WithMany("JockeyInvitations")
                        .HasForeignKey("JockeyId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_invitations_jockeys");

                    b.HasOne("Eliteracingleague.API.Models.RaceRegistration", "Registration")
                        .WithMany("JockeyInvitations")
                        .HasForeignKey("RegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_invitations_registrations");

                    b.Navigation("InvitedByOwner");

                    b.Navigation("Jockey");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.JockeyRecommendation", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.Horse", "Horse")
                        .WithMany("JockeyRecommendations")
                        .HasForeignKey("HorseId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_recommendations_horses");

                    b.HasOne("Eliteracingleague.API.Models.Jockey", "Jockey")
                        .WithMany("JockeyRecommendations")
                        .HasForeignKey("JockeyId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_recommendations_jockeys");

                    b.HasOne("Eliteracingleague.API.Models.Race", "Race")
                        .WithMany("JockeyRecommendations")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_recommendations_races");

                    b.HasOne("Eliteracingleague.API.Models.RaceRegistration", "Registration")
                        .WithMany("JockeyRecommendations")
                        .HasForeignKey("RegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK_jockey_recommendations_registrations");

                    b.Navigation("Horse");

                    b.Navigation("Jockey");

                    b.Navigation("Race");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Notification", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_notifications_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.PreRaceInspection", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.Race", "Race")
                        .WithMany("PreRaceInspections")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK_pre_race_inspections_races");

                    b.HasOne("Eliteracingleague.API.Models.RaceReferee", "Referee")
                        .WithMany("PreRaceInspections")
                        .HasForeignKey("RefereeId")
                        .IsRequired()
                        .HasConstraintName("FK_pre_race_inspections_referees");

                    b.HasOne("Eliteracingleague.API.Models.RaceRegistration", "Registration")
                        .WithMany("PreRaceInspections")
                        .HasForeignKey("RegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK_pre_race_inspections_registrations");

                    b.Navigation("Race");

                    b.Navigation("Referee");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.PrizeAward", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.Jockey", "Jockey")
                        .WithMany("PrizeAwards")
                        .HasForeignKey("JockeyId")
                        .HasConstraintName("FK_prize_awards_jockeys");

                    b.HasOne("Eliteracingleague.API.Models.HorseOwner", "Owner")
                        .WithMany("PrizeAwards")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_prize_awards_owners");

                    b.HasOne("Eliteracingleague.API.Models.Race", "Race")
                        .WithMany("PrizeAwards")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK_prize_awards_races");

                    b.HasOne("Eliteracingleague.API.Models.RaceRegistration", "Registration")
                        .WithMany("PrizeAwards")
                        .HasForeignKey("RegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK_prize_awards_registrations");

                    b.Navigation("Jockey");

                    b.Navigation("Owner");

                    b.Navigation("Race");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.PrizeRule", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.Race", "Race")
                        .WithMany("PrizeRules")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK_prize_rules_races");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Race", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.Tournament", "Tournament")
                        .WithOne("Race")
                        .HasForeignKey("Eliteracingleague.API.Models.Race", "TournamentId")
                        .IsRequired()
                        .HasConstraintName("FK_races_tournaments");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RacePrediction", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.RaceRegistration", "ActualWinnerRegistration")
                        .WithMany("RacePredictionActualWinnerRegistrations")
                        .HasForeignKey("ActualWinnerRegistrationId")
                        .HasConstraintName("FK_race_predictions_actual_winner");

                    b.HasOne("Eliteracingleague.API.Models.RaceRegistration", "PredictedRegistration")
                        .WithMany("RacePredictionPredictedRegistrations")
                        .HasForeignKey("PredictedRegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK_race_predictions_predicted_registration");

                    b.HasOne("Eliteracingleague.API.Models.Race", "Race")
                        .WithMany("RacePredictions")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK_race_predictions_races");

                    b.HasOne("Eliteracingleague.API.Models.User", "Spectator")
                        .WithMany("RacePredictions")
                        .HasForeignKey("SpectatorId")
                        .IsRequired()
                        .HasConstraintName("FK_race_predictions_spectators");

                    b.Navigation("ActualWinnerRegistration");

                    b.Navigation("PredictedRegistration");

                    b.Navigation("Race");

                    b.Navigation("Spectator");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RaceReferee", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.User", "Referee")
                        .WithOne("RaceReferee")
                        .HasForeignKey("Eliteracingleague.API.Models.RaceReferee", "RefereeId")
                        .IsRequired()
                        .HasConstraintName("FK_race_referees_users");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RaceRegistration", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.Horse", "Horse")
                        .WithMany("RaceRegistrations")
                        .HasForeignKey("HorseId")
                        .IsRequired()
                        .HasConstraintName("FK_race_registrations_horses");

                    b.HasOne("Eliteracingleague.API.Models.Jockey", "Jockey")
                        .WithMany("RaceRegistrations")
                        .HasForeignKey("JockeyId")
                        .HasConstraintName("FK_race_registrations_jockeys");

                    b.HasOne("Eliteracingleague.API.Models.HorseOwner", "Owner")
                        .WithMany("RaceRegistrations")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_race_registrations_owners");

                    b.HasOne("Eliteracingleague.API.Models.Race", "Race")
                        .WithMany("RaceRegistrations")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK_race_registrations_races");

                    b.HasOne("Eliteracingleague.API.Models.User", "ReviewedByNavigation")
                        .WithMany("RaceRegistrations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK_race_registrations_reviewed_by");

                    b.Navigation("Horse");

                    b.Navigation("Jockey");

                    b.Navigation("Owner");

                    b.Navigation("Race");

                    b.Navigation("ReviewedByNavigation");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RaceResult", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.User", "AdminConfirmedByNavigation")
                        .WithMany("RaceResults")
                        .HasForeignKey("AdminConfirmedBy")
                        .HasConstraintName("FK_race_results_admin_confirmed_by");

                    b.HasOne("Eliteracingleague.API.Models.RaceReferee", "EnteredByReferee")
                        .WithMany("RaceResults")
                        .HasForeignKey("EnteredByRefereeId")
                        .IsRequired()
                        .HasConstraintName("FK_race_results_referees");

                    b.HasOne("Eliteracingleague.API.Models.Race", "Race")
                        .WithMany("RaceResults")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK_race_results_races");

                    b.HasOne("Eliteracingleague.API.Models.RaceRegistration", "Registration")
                        .WithOne("RaceResult")
                        .HasForeignKey("Eliteracingleague.API.Models.RaceResult", "RegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK_race_results_registrations");

                    b.Navigation("AdminConfirmedByNavigation");

                    b.Navigation("EnteredByReferee");

                    b.Navigation("Race");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RaceViolation", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.Race", "Race")
                        .WithMany("RaceViolations")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK_race_violations_races");

                    b.HasOne("Eliteracingleague.API.Models.RaceReferee", "Referee")
                        .WithMany("RaceViolations")
                        .HasForeignKey("RefereeId")
                        .IsRequired()
                        .HasConstraintName("FK_race_violations_referees");

                    b.HasOne("Eliteracingleague.API.Models.RaceRegistration", "Registration")
                        .WithMany("RaceViolations")
                        .HasForeignKey("RegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK_race_violations_registrations");

                    b.Navigation("Race");

                    b.Navigation("Referee");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RefereeAssignment", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.User", "AssignedByNavigation")
                        .WithMany("RefereeAssignments")
                        .HasForeignKey("AssignedBy")
                        .IsRequired()
                        .HasConstraintName("FK_referee_assignments_assigned_by");

                    b.HasOne("Eliteracingleague.API.Models.Race", "Race")
                        .WithMany("RefereeAssignments")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK_referee_assignments_races");

                    b.HasOne("Eliteracingleague.API.Models.RaceReferee", "Referee")
                        .WithMany("RefereeAssignments")
                        .HasForeignKey("RefereeId")
                        .IsRequired()
                        .HasConstraintName("FK_referee_assignments_referees");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Race");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RefereeReport", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.Race", "Race")
                        .WithMany("RefereeReports")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK_referee_reports_races");

                    b.HasOne("Eliteracingleague.API.Models.RaceReferee", "Referee")
                        .WithMany("RefereeReports")
                        .HasForeignKey("RefereeId")
                        .IsRequired()
                        .HasConstraintName("FK_referee_reports_referees");

                    b.Navigation("Race");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Tournament", b =>
                {
                    b.HasOne("Eliteracingleague.API.Models.User", "CreatedByNavigation")
                        .WithMany("Tournaments")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_tournaments_users");

                    b.HasOne("Eliteracingleague.API.Models.Season", "Season")
                        .WithMany("Tournaments")
                        .HasForeignKey("SeasonId")
                        .IsRequired()
                        .HasConstraintName("FK_tournaments_seasons");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Horse", b =>
                {
                    b.Navigation("JockeyRecommendations");

                    b.Navigation("RaceRegistrations");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.HorseBreed", b =>
                {
                    b.Navigation("Horses");

                    b.Navigation("JockeyBreedExperiences");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.HorseOwner", b =>
                {
                    b.Navigation("Horses");

                    b.Navigation("JockeyInvitations");

                    b.Navigation("PrizeAwards");

                    b.Navigation("RaceRegistrations");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Jockey", b =>
                {
                    b.Navigation("JockeyAvailabilities");

                    b.Navigation("JockeyBreedExperiences");

                    b.Navigation("JockeyDistanceExperiences");

                    b.Navigation("JockeyInvitations");

                    b.Navigation("JockeyRecommendations");

                    b.Navigation("PrizeAwards");

                    b.Navigation("RaceRegistrations");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Race", b =>
                {
                    b.Navigation("JockeyRecommendations");

                    b.Navigation("PreRaceInspections");

                    b.Navigation("PrizeAwards");

                    b.Navigation("PrizeRules");

                    b.Navigation("RacePredictions");

                    b.Navigation("RaceRegistrations");

                    b.Navigation("RaceResults");

                    b.Navigation("RaceViolations");

                    b.Navigation("RefereeAssignments");

                    b.Navigation("RefereeReports");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RaceReferee", b =>
                {
                    b.Navigation("PreRaceInspections");

                    b.Navigation("RaceResults");

                    b.Navigation("RaceViolations");

                    b.Navigation("RefereeAssignments");

                    b.Navigation("RefereeReports");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.RaceRegistration", b =>
                {
                    b.Navigation("JockeyInvitations");

                    b.Navigation("JockeyRecommendations");

                    b.Navigation("PreRaceInspections");

                    b.Navigation("PrizeAwards");

                    b.Navigation("RacePredictionActualWinnerRegistrations");

                    b.Navigation("RacePredictionPredictedRegistrations");

                    b.Navigation("RaceResult");

                    b.Navigation("RaceViolations");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Season", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.Tournament", b =>
                {
                    b.Navigation("Race");
                });

            modelBuilder.Entity("Eliteracingleague.API.Models.User", b =>
                {
                    b.Navigation("EmailVerificationOtps");

                    b.Navigation("HorseOwner");

                    b.Navigation("Jockey");

                    b.Navigation("Notifications");

                    b.Navigation("RacePredictions");

                    b.Navigation("RaceReferee");

                    b.Navigation("RaceRegistrations");

                    b.Navigation("RaceResults");

                    b.Navigation("RefereeAssignments");

                    b.Navigation("Tournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
