using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Eliteracingleague.API.Controllers;

[Route("api/uploads")]
[ApiController]
[Authorize]
public class UploadsController : ControllerBase
{
    private const long MaxFileSize = 10 * 1024 * 1024;
    private const long MaxRewardImageFileSize = 5 * 1024 * 1024;
    private readonly IWebHostEnvironment _env;

    public UploadsController(IWebHostEnvironment env)
    {
        _env = env;
    }

    [HttpPost]
    [Consumes("multipart/form-data")]
    public async Task<IActionResult> Upload(
        IFormFile? file,
        [FromForm] string? category,
        CancellationToken cancellationToken)
    {
        if (file == null || file.Length == 0)
        {
            return BadRequest(new { message = "File không được để trống." });
        }

        if (file.Length > MaxFileSize)
        {
            return BadRequest(new { message = "Dung lượng file tối đa là 10MB." });
        }

        if (!TryResolveCategory(category, out var uploadCategory))
        {
            return BadRequest(new { message = "Category không hợp lệ." });
        }

        if (uploadCategory == UploadCategory.Rewards && !User.IsInRole("Admin"))
        {
            return Forbid();
        }

        if (uploadCategory == UploadCategory.Rewards && file.Length > MaxRewardImageFileSize)
        {
            return BadRequest(new { message = "Ảnh phần thưởng có dung lượng tối đa 5MB." });
        }

        if (!TryResolveSafeExtension(file.FileName, uploadCategory, out var safeExtension))
        {
            return BadRequest(new { message = "Định dạng file không hợp lệ." });
        }

        var webRootPath = string.IsNullOrWhiteSpace(_env.WebRootPath)
            ? Path.Combine(Directory.GetCurrentDirectory(), "wwwroot")
            : _env.WebRootPath;

        // Folder name is selected only from server-controlled constants.
        // User input is never used directly to construct a filesystem path.
        var uploadFolderName = uploadCategory switch
        {
            UploadCategory.Horses => "horses",
            UploadCategory.Jockeys => "jockeys",
            UploadCategory.Rewards => "rewards",
            _ => throw new InvalidOperationException("Unsupported upload category.")
        };

        var uploadsRoot = Path.GetFullPath(Path.Combine(webRootPath, "uploads"));
        var uploadFolder = Path.GetFullPath(Path.Combine(uploadsRoot, uploadFolderName));

        EnsurePathIsInsideRoot(uploadsRoot, uploadFolder);
        Directory.CreateDirectory(uploadFolder);

        // The stored filename is generated by the server. The original filename
        // supplied by the client is never used as part of the destination path.
        var storedFileName = $"{Guid.NewGuid():N}{safeExtension}";
        var filePath = Path.GetFullPath(Path.Combine(uploadFolder, storedFileName));

        EnsurePathIsInsideRoot(uploadFolder, filePath);

        await using (var stream = new FileStream(
                         filePath,
                         FileMode.CreateNew,
                         FileAccess.Write,
                         FileShare.None,
                         bufferSize: 81920,
                         useAsync: true))
        {
            await file.CopyToAsync(stream, cancellationToken);
        }

        var url = $"/uploads/{uploadFolderName}/{storedFileName}";
        var absoluteUrl = $"{Request.Scheme}://{Request.Host}{Request.PathBase}{url}";

        return Ok(new
        {
            message = "Upload file thành công.",
            url,
            absoluteUrl,
            fileName = storedFileName,
            contentType = file.ContentType,
            size = file.Length
        });
    }

    private static bool TryResolveCategory(string? category, out UploadCategory uploadCategory)
    {
        uploadCategory = category?.Trim().ToLowerInvariant() switch
        {
            "horses" => UploadCategory.Horses,
            "jockeys" => UploadCategory.Jockeys,
            "rewards" => UploadCategory.Rewards,
            _ => UploadCategory.Invalid
        };

        return uploadCategory != UploadCategory.Invalid;
    }

    private static bool TryResolveSafeExtension(
        string originalFileName,
        UploadCategory category,
        out string safeExtension)
    {
        var extension = Path.GetExtension(originalFileName).ToLowerInvariant();

        safeExtension = (category, extension) switch
        {
            (UploadCategory.Horses, ".jpg") => ".jpg",
            (UploadCategory.Horses, ".jpeg") => ".jpeg",
            (UploadCategory.Horses, ".png") => ".png",
            (UploadCategory.Horses, ".webp") => ".webp",
            (UploadCategory.Jockeys, ".jpg") => ".jpg",
            (UploadCategory.Jockeys, ".jpeg") => ".jpeg",
            (UploadCategory.Jockeys, ".png") => ".png",
            (UploadCategory.Jockeys, ".webp") => ".webp",
            (UploadCategory.Jockeys, ".pdf") => ".pdf",
            (UploadCategory.Rewards, ".jpg") => ".jpg",
            (UploadCategory.Rewards, ".jpeg") => ".jpeg",
            (UploadCategory.Rewards, ".png") => ".png",
            (UploadCategory.Rewards, ".webp") => ".webp",
            _ => string.Empty
        };

        return safeExtension.Length > 0;
    }

    private static void EnsurePathIsInsideRoot(string rootPath, string candidatePath)
    {
        var normalizedRoot = Path.GetFullPath(rootPath)
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
            + Path.DirectorySeparatorChar;

        var normalizedCandidate = Path.GetFullPath(candidatePath);

        if (!normalizedCandidate.StartsWith(normalizedRoot, StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidOperationException("Đường dẫn upload không hợp lệ.");
        }
    }

    private enum UploadCategory
    {
        Invalid = 0,
        Horses = 1,
        Jockeys = 2,
        Rewards = 3
    }
}